server:
  port: 5042

spring:
  rabbitmq:
    addresses: localhost

powsybl:
  services:
    case-server:
      base-uri: http://localhost:5000

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    security-analysis-server:
      base-uri: http://localhost:5023
    network-modification-server:
      base-uri: http://localhost:5007
    filter-server:
      base-uri: http://localhost:5027
