server:
  port: 5043

spring:
  rabbitmq:
    addresses: localhost
  cloud:
    aws:
      s3:
        endpoint: http://localhost:19000

powsybl-ws:
  database:
    host: localhost

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    security-analysis-server:
      base-uri: http://localhost:5023
    network-modification-server:
       base-uri: http://localhost:5007
    state-estimation-server:
      base-uri: http://localhost:6040
