server:
  port: 5043

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    security-analysis-server:
      base-uri: http://localhost:5023
    state-estimation-server:
      base-uri: http://localhost:6040