spring:
  application:
    name: monitor-server
  cloud:
    function:
      definition: consumeMonitorUpdate;consumeRunUsingServers;consumeNetworkModifications;consumeSecurityAnalysis
    stream:
      bindings:
        publishRunSecurityAnalysis-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.securityanalysis.run
        consumeMonitorUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.update
          group: monitorUpdateGroup
        publishRunSecurityAnalysisUsingServers-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.securityanalysis.using.servers.run
        consumeRunUsingServers-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.securityanalysis.using.servers.run
        consumeNetworkModifications-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}modifications.case.result
        consumeSecurityAnalysis-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.case.result
      output-bindings: publishRunSecurityAnalysis-out-0;publishRunSecurityAnalysisUsingServers-out-0;

powsybl-ws:
  database:
    queryBegin: '&'
    customQuery: ${powsybl-ws.database.customQueryBegin}reWriteBatchedInserts=true
    name: monitor