spring:
  application:
    name: monitor-server
  cloud:
    stream:
      bindings:
        publishRunSa-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.process.sa.run
        consumeMonitorUpdate-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}monitor.update
          group: monitorUpdateGroup

powsybl-ws:
  database:
    queryBegin: '&'
    customQuery: ${powsybl-ws.database.customQueryBegin}reWriteBatchedInserts=true
    name: process